image: ubuntu:20.04

stages:
  - build

before_script:
  - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -yq install git build-essential cmake lcov

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O0 -g -pg -fprofile-arcs -ftest-coverage' -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg .. && make
